### ISSUE TITLE
Error when loop arrives 2020

### ISSUE THREAD

**Issue by mrisus** [Benny-/Yahoo-ticker-symbol-downloader#17]
I think Yahoo has restricted the pagination. 

I have error when the program arrives 2020:
https://finance.yahoo.com/lookup/?m=ALL&b=2020&t=B&s=b&r=

**Comment by Benny-** [comment]
True. There is no way to circumvent this on my side.

The script can handle the restriction on continue on after several tries. The script is made so it will magically work once the restriction is lifted. It will try multiple times, the reason for this is related to #4.
