### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position ....

### ISSUE THREAD

**Issue by olejardamir** [Benny-/Yahoo-ticker-symbol-downloader#19]
Exporting Stock symbols
Traceback (most recent call last):
  File "/usr/local/bin/YahooTickerDownloader.py", line 147, in <module>
    main()
  File "/usr/local/bin/YahooTickerDownloader.py", line 135, in main
    f.write(data.csv.encode('UTF-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1543: ordinal not in range(128)

**Comment by aandragk** [comment]
Same Problem for me. Maybe an Issue with Python2. 
Try to use Python3 or put this on top of the YahooTickerDownloader.py file.

```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

**Comment by Benny-** [comment]
@olejardamir , was it a python2 problem? Is it resolved now?

**Comment by olejardamir** [comment]
Yes that is what it was. A second problem was reading the compressed file
once the download completed.  Sorry for not replying, I simply did not have
time.
