### ISSUE TITLE
Please add utf8 default coding

### ISSUE THREAD

**Issue by manzikki** [Benny-/Yahoo-ticker-symbol-downloader#23]
After download, writing the files fails:
  File "/home/ubuntu/.local/bin/YahooTickerDownloader.py", line 135, in main
    f.write(data.csv.encode('UTF-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1233: ordinal not in range(128)

This can be avoided by:

import sys

..
def main():
    reload(sys)  
    sys.setdefaultencoding('utf8')

**Comment by Benny-** [comment]
This is a good solution for issue #16

**Comment by Benny-** [comment]
Resolved in b22a1629918f0198fabb8e5f4676f3c6ca273d6a
