### ISSUE TITLE
a little suggestion

### ISSUE THREAD

**Issue by istzustand** [Benny-/Yahoo-ticker-symbol-downloader#31]
Hi. 
I'm new to this git and programming stuff, so please bear with me :)

if I query stocks I'm getting  22049 symbols from 9 exchanges. Since I'd love to have more  I fiddled a bit around and got your tool to get 28094 symbols from 66 exchanges. 

All I had to do was in the ytd/SymbolDownloader.py  add " 'm' : 'all' " to params.

This now enables me to filter for stocks which are traded e.g. in Frankfurt which I find awesome ;)

dunno if you want to drop that line but I thought I'd share my idea (: 

edith says: I'll try this branching and pull request stuff... let"s see...
edit2: I made a mistake. I was formerly pulling from de.finance.yahoo. Now back at finance.yahoo I get 105539 stocks from 69 exchanges. Still about 9k missing.

**Comment by Benny-** [comment]
Thank you! I'll merge it right away when I get home.

And welcome to github

Sent using the GMX mail app
