### ISSUE TITLE
Unable to download stocks

### ISSUE THREAD

**Issue by fro391** [Benny-/Yahoo-ticker-symbol-downloader#35]
$ YahooTickerDownloader.py stocks
Checking if we can resume a old download session
Downloader found on disk, resuming
Downloading stocks

req https://finance.yahoo.com/_finance_doubledown/api/resource/finance.yfinlist.symbol_lookup;p=1;s=a;b=0;m=all;t=S?device=console&returnMeta=true
A exception occurred while downloading. Suspending downloader to disk
Successfully saved download state
Try removing {type}.pickle file if this error persists
Issues can be reported on https://github.com/Benny-/Yahoo-ticker-symbol-downloader/issues

Traceback (most recent call last):
  File "C:/Users/Richard/Anaconda2/Scripts/YahooTickerDownloader.py", line 161, in <module>
    main()
  File "C:/Users/Richard/Anaconda2/Scripts/YahooTickerDownloader.py", line 111, in main
    downloadEverything(downloader, tickerType, args.insecure, args.sleep, args.pandantic, market)
  File "C:/Users/Richard/Anaconda2/Scripts/YahooTickerDownloader.py", line 46, in downloadEverything
    symbols = downloader.nextRequest(insecure, pandantic, market)
  File "C:\users\richard\anaconda2\lib\site-packages\ytd\SymbolDownloader.py", line 113, in nextRequest
    requests.exceptions.ReadTimeout,
AttributeError: 'module' object has no attribute 'ReadTimeout'

**Comment by Benny-** [comment]
[Requets@2.2.1](https://github.com/requests/requests/blob/v2.2.1/requests/exceptions.py) does not have ReadTimeout. I am updating the requests dependency listed in setup.py.

You can manually upgrade requests to the latest version using the following command:

```sh
pip install --upgrade requests
```

**Comment by Benny-** [comment]
That should solve your issue. Please report if you are still having trouble.

**Comment by Benny-** [comment]
I tested things and 2.4.0 was the minimum version of requests where everything worked without errors like the one you listed.

Please note that you need to remove your .pickle file. It seems I am serializing a session object and it is not compatible between different versions of requests. I have raised [another issue](https://github.com/Benny-/Yahoo-ticker-symbol-downloader/issues/36) about this.

**Comment by fro391** [comment]
Thank you. Updating request solved my problem.
