### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Ryzbc** [Benny-/Yahoo-ticker-symbol-downloader#42]
Hi Benny,
I am trying to install your module but the pip crack. Attached I will copy last part of the error message. My platform is Mac with macOS High Sierra, version 10.13.3 and use Terminal for the pip.
The message is:
 creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp/src
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src/agent.o -std=c++11
    In file included from reppy/rep-cpp/src/agent.cpp:4:
    reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by Benny-** [comment]
Thank you for this bug report. It appears to be a error in building the latest added dependency (reppy for robots.txt parsing).

The quickest and easiest workaround would be to install 2.1.1 of Yahoo-ticker-symbol-downloader while this bug is being investigated and fixed. That version does not have that dependency.

```sh
pip install Yahoo-ticker-downloader==2.1.1
```

Can you please try doing the following and report back the full results? (regardless if it succeeds or not)
```sh
pip install reppy
```

**Comment by Ryzbc** [comment]
Thanks Benny, I will try it and report you the result.

Enviado por Rafa Barneto

El 18 mar 2018, a las 12:29, Benny Jacobs <notifications@github.com<mailto:notifications@github.com>> escribió:


Thank you for this bug report. It appears to be a error in building the latest added dependency (reppy for robots.txt parsing).

The quickest and easiest workaround would be to install 2.1.1 of Yahoo-ticker-symbol-downloader while this bug is being investigated and fixed. That version does not have that dependency.

pip install Yahoo-ticker-downloader==2.1.1

Can you please try doing the following and report back the full results? (regardless if it succeeds or not)

pip install reppy

**Comment by Ryzbc** [comment]
-/Yahoo-ticker-symbol-downloader] install error (#42)

good morning Benny!

following your instructions I installed the previous version 2.1.1 of your program and it works, at least without options: I has been able to download all stocks tickers, but when I try to select an specific market [-m us], the program do not recognize that parameter and d’ont work. Probably it is a new feature or I make some error in typing it.
On the other hand, when I try to install reppy, I get the following messages:

"  Building from C++
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-2.7
  creating build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/exceptions.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/ttl.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/util.py -> build/lib.macosx-10.6-intel-2.7/reppy
  creating build/lib.macosx-10.6-intel-2.7/reppy/cache
  copying reppy/cache/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
  copying reppy/cache/policy.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
  running build_ext
  building 'reppy.robots' extension
  creating build/temp.macosx-10.6-intel-2.7
  creating build/temp.macosx-10.6-intel-2.7/reppy
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp/src
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src/agent.o -std=c++11
  In file included from reppy/rep-cpp/src/agent.cpp:4:
  reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1



  ----------------------------------------
  Failed building wheel for reppy
  Running setup.py clean for reppy
Failed to build reppy
Installing collected packages: reppy
  Running setup.py install for reppy ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-vcltOQ-record/install-record.txt --single-version-externally-managed --compile:
    Building from C++
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/exceptions.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/ttl.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/util.py -> build/lib.macosx-10.6-intel-2.7/reppy
    creating build/lib.macosx-10.6-intel-2.7/reppy/cache
    copying reppy/cache/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
    copying reppy/cache/policy.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
    running build_ext
    building 'reppy.robots' extension
    creating build/temp.macosx-10.6-intel-2.7
    creating build/temp.macosx-10.6-intel-2.7/reppy
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp/src
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src/agent.o -std=c++11
    In file included from reppy/rep-cpp/src/agent.cpp:4:
    reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1



    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-vcltOQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/“
Best regards.

Rafa Barneto

El 18 mar 2018, a las 21:00, Rafa Ryzbc <ryzbc@outlook.es<mailto:ryzbc@outlook.es>> escribió:



Enviado por Rafa Barneto

Inicio del mensaje reenviado:

De: Benny Jacobs <notifications@github.com<mailto:notifications@github.com>>
Fecha: 18 de marzo de 2018, 12:29:54 CET
Para: Benny-/Yahoo-ticker-symbol-downloader <Yahoo-ticker-symbol-downloader@noreply.github.com<mailto:Yahoo-ticker-symbol-downloader@noreply.github.com>>
Cc: Ryzbc <ryzbc@outlook.es<mailto:ryzbc@outlook.es>>,  Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Asunto: Re: [Benny-/Yahoo-ticker-symbol-downloader] install error (#42)
Responder a: Benny-/Yahoo-ticker-symbol-downloader <reply@reply.github.com<mailto:reply@reply.github.com>>


Thank you for this bug report. It appears to be a error in building the latest added dependency (reppy for robots.txt parsing).

The quickest and easiest workaround would be to install 2.1.1 of Yahoo-ticker-symbol-downloader while this bug is being investigated and fixed. That version does not have that dependency.

pip install Yahoo-ticker-downloader==2.1.1

Can you please try doing the following and report back the full results? (regardless if it succeeds or not)

pip install reppy

**Comment by Ryzbc** [comment]
good morning Benny!

following your instructions I installed the previous version 2.1.1 of your program and it works, at least without options: I has been able to download all stocks tickers, but when I try to select an specific market [-m us], the program do not recognize that parameter and d’ont work. Probably it is a new feature or I make some error in typing it.
On the other hand, when I try to install reppy, I get the following messages:

"  Building from C++
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-2.7
  creating build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/exceptions.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/ttl.py -> build/lib.macosx-10.6-intel-2.7/reppy
  copying reppy/util.py -> build/lib.macosx-10.6-intel-2.7/reppy
  creating build/lib.macosx-10.6-intel-2.7/reppy/cache
  copying reppy/cache/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
  copying reppy/cache/policy.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
  running build_ext
  building 'reppy.robots' extension
  creating build/temp.macosx-10.6-intel-2.7
  creating build/temp.macosx-10.6-intel-2.7/reppy
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp
  creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp/src
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src/agent.o -std=c++11
  In file included from reppy/rep-cpp/src/agent.cpp:4:
  reppy/rep-cpp/deps/url-cpp/include/url.h:8:10<x-apple-data-detectors://0>: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1



  ----------------------------------------
  Failed building wheel for reppy
  Running setup.py clean for reppy
Failed to build reppy
Installing collected packages: reppy
  Running setup.py install for reppy ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-vcltOQ-record/install-record.txt --single-version-externally-managed --compile:
    Building from C++
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/exceptions.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/ttl.py -> build/lib.macosx-10.6-intel-2.7/reppy
    copying reppy/util.py -> build/lib.macosx-10.6-intel-2.7/reppy
    creating build/lib.macosx-10.6-intel-2.7/reppy/cache
    copying reppy/cache/__init__.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
    copying reppy/cache/policy.py -> build/lib.macosx-10.6-intel-2.7/reppy/cache
    running build_ext
    building 'reppy.robots' extension
    creating build/temp.macosx-10.6-intel-2.7
    creating build/temp.macosx-10.6-intel-2.7/reppy
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp
    creating build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/deps/url-cpp/src
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.6-intel-2.7/reppy/rep-cpp/src/agent.o -std=c++11
    In file included from reppy/rep-cpp/src/agent.cpp:4:
    reppy/rep-cpp/deps/url-cpp/include/url.h:8:10<x-apple-data-detectors://1>: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1



    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-vcltOQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/yg/m793vdss71xcx7w9flp9cmsm0000gq/T/pip-build-wF9pWb/reppy/“
Best regards.

Enviado por Rafa Barneto

El 18 mar 2018, a las 12:29, Benny Jacobs <notifications@github.com<mailto:notifications@github.com>> escribió:


Thank you for this bug report. It appears to be a error in building the latest added dependency (reppy for robots.txt parsing).

The quickest and easiest workaround would be to install 2.1.1 of Yahoo-ticker-symbol-downloader while this bug is being investigated and fixed. That version does not have that dependency.

pip install Yahoo-ticker-downloader==2.1.1

Can you please try doing the following and report back the full results? (regardless if it succeeds or not)

pip install reppy

**Comment by Benny-** [comment]
I have delegated the problem with installing reppy to https://github.com/seomoz/reppy/issues/84

**Comment by Benny-** [comment]
How do you know te `-m` switch does not work? What is the command you are using? What is the expected result? What is the actual result? You can make another issue for the `-m` switch not working.

**Comment by Ryzbc** [comment]
I am trying to select just the US-Canada markets with [-m us], but I am not sure what is the correct syntax.

Enviado por Rafa Barneto

El 20 mar 2018, a las 12:56, Benny Jacobs <notifications@github.com<mailto:notifications@github.com>> escribió:


How do you know te -m switch does not work? What is the command you are using? What is the expected result? What is the actual result? You can make another issue for the -m switch not working.

**Comment by Benny-** [comment]
That should be the correct syntax.
```sh
YahooTickerDownloader.py -m us stocks
```
How do you know it does not work?

**Comment by Ryzbc** [comment]
Yes, it works, it was my mistake.
Sorry and many thanks.

Enviado por Rafa Barneto

El 20 mar 2018, a las 13:10, Benny Jacobs <notifications@github.com<mailto:notifications@github.com>> escribió:


That should be the correct syntax.

YahooTickerDownloader.py -m us stocks

How do you know it does not work?

**Comment by Benny-** [comment]
Great! I'll close this issue now.

For the pip installation error you need to upgrade your Mac OS and/or Xcode. Some old versions seems to be missing a header. For details refer to https://github.com/seomoz/reppy/issues/84 again.
