### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by gkourogiorgas** [Benny-/Yahoo-ticker-symbol-downloader#46]
Hi
I installed by pip install Yahoo-Ticker-Downloader and I got the following errors(?):
![image](https://user-images.githubusercontent.com/24841178/40727665-476779dc-6420-11e8-8b5b-a338d6312f23.png)
Any help?
I tried then running the py file but it wasn't recognized
Thanks
George

**Comment by Benny-** [comment]
Your posted logs say Microsoft Visual C++ 14.0 is required. A bing search led me to [a download site](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Can you try this and post the results here?

**Comment by Benny-** [comment]
Related to this reppy issue: https://github.com/seomoz/reppy/issues/90

**Comment by gkourogiorgas** [comment]
hey all. I solved the issue by installing Build tools for visual c++ 2015 (v14). The link does not work. You have to look for build tools for visual studio 2017 (v15) and look at the options in the installer.
