### ISSUE TITLE
Why can I only download generic symbols? Where is the option to download only stock symbols?

### ISSUE THREAD

**Issue by psikonetik** [Benny-/Yahoo-ticker-symbol-downloader#47]
Hi, 
I am trying to get only stocks tickers passing the arg stocks to the command line however looking at the code it seems only generic(all) is available, is this expected?

Thanks

**Comment by Benny-** [comment]
Yes, unfortunaly there was a change in the Yahoo API. Rendering it impossible to get only stocks.

There is currently no known way on how to work around this change.
